const $=s=>document.querySelector(s);let sb=null,user=null;
async function init(){const c=await (await fetch('/api/config')).json();sb=window.supabase.createClient(c.supabaseUrl,c.supabasePublishableKey);const {data}=await sb.auth.getSession();user=data.session?.user||null;if(!user){location.href='/';return}await Promise.all([loadMe(),loadHistory(),loadTasks()]);}
async function session(){const {data}=await sb.auth.getSession();return data.session;}
async function api(path,opts={}){const s=await session();return fetch(path,{...opts,headers:{...(opts.headers||{}),Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'}})}
async function loadMe(){const r=await api('/api/me');const d=await r.json();$('#accountInfo').textContent=`${d.scans_left===null?'Pro account':`${d.scans_left} of ${d.free_limit} free scans left`} · signed in as ${user.email||'your account'}`;}
async function loadHistory(){const r=await api('/api/history');const d=await r.json();if(!r.ok)return $('#historyList').innerHTML='<div class="empty">Could not load history.</div>';const rows=d.items||[];$('#historyList').innerHTML=rows.length?rows.map(x=>`<div class="history-row"><div><strong>${esc(x.product_name||'Unnamed product')}</strong><small>${new Date(x.created_at).toLocaleString()} · ${esc(x.limiting||'Label analysis')}</small></div><div><b>${esc(x.verdict||'—')}</b><br><button class="text-link delete" data-id="${x.id}">Delete</button></div></div>`).join(''):'<div class="empty">No scans yet. Your first result will appear here.</div>';document.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{await api('/api/history/'+b.dataset.id,{method:'DELETE'});loadHistory();});}
async function loadTasks(){const r=await api('/api/tasks');const d=await r.json();if(!r.ok)return $('#tasksList').innerHTML='<div class="empty">Could not load tasks.</div>';$('#tasksList').innerHTML=(d.items||[]).map(t=>`<label class="task"><input type="checkbox" ${t.completed?'checked':''} data-id="${t.id}"><span><b>${esc(t.title)}</b><br><small>${esc(t.details||'')}${t.due_date?' · Due '+esc(t.due_date):''}</small></span></label>`).join('')||'<div class="empty">Ask Durva to create a task plan.</div>';document.querySelectorAll('#tasksList input').forEach(i=>i.onchange=async()=>{await api('/api/tasks/'+i.dataset.id,{method:'PATCH',body:JSON.stringify({completed:i.checked})});});}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
async function scan(){const f=$('#file').files?.[0];if(!f)return $('#result').innerHTML='<p class="auth-message">Choose a label image first.</p>';if(f.size>5*1024*1024)return $('#result').innerHTML='<p class="auth-message">Please use an image under 5 MB.</p>';$('#result').innerHTML='<div class="result">Reading the label…</div>';const r=await api('/api/scan',{method:'POST',body:JSON.stringify({image:await fileData(f),mime:f.type})});const d=await r.json();if(r.status===402){$('#toast').classList.remove('hidden');return}if(!r.ok){$('#result').innerHTML=`<div class="result"><b>${esc(d.error||'Scan failed.')}</b></div>`;return}$('#result').innerHTML=`<div class="result"><div class="result-top"><div><small>TRUTHLENS VERDICT</small><div class="verdict ${d.analysis.verdict.level}">${d.analysis.verdict.level}</div><p class="sub">${esc(d.analysis.product||'Product')} · limiting factor: ${esc(d.analysis.limiting)}</p></div><b>${d.analysis.safe_grams}g</b></div><div class="nutri-grid">${n('Sugar',d.nutrients.total_sugars,'g')}${n('Sat. fat',d.nutrients.sat_fat,'g')}${n('Sodium',d.nutrients.sodium,'mg')}${n('Protein',d.nutrients.protein,'g')}</div><p class="sub">${esc(d.analysis.note)}</p><p class="sub"><b>${d.scans_left}</b> free scans left.</p></div>`;await loadMe();await loadHistory();}
function n(a,v,u){return `<div class="nutri"><small>${a}</small><b>${v??'—'}${v!=null?u:''}</b></div>`}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
$('#run').onclick=scan;$('#scanBtn').onclick=()=>$('#file').scrollIntoView({behavior:'smooth',block:'center'});$('#logout').onclick=async()=>{await sb.auth.signOut();location.href='/'};$('#toastClose').onclick=()=>$('#toast').classList.add('hidden');init();
